import { StyleSheet } from "react-native";
import { ThemeColors } from "@/constants/ThemeColors";

export const getWashingTempStyles = (ThemeColors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: "flex-start",
      alignItems: "center",
      padding: 10,
      backgroundColor: ThemeColors.background,
      marginTop: 20,
    },
    content: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 16,
      backgroundColor: ThemeColors.background,
      width: "100%",
    },
    calendarButton: {
      backgroundColor: "white",
      borderRadius: 5,
      marginTop: 10,
      width: 150,
      height: 55,
      justifyContent: "center",
      alignItems: "center",
    },
    dateFilterContainer: {
      width: "60%",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 16,
      marginTop: 20,
      marginBottom: 10,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: ThemeColors.navSelected,
    },
    dataList: {
      padding: 16,
      backgroundColor: ThemeColors.background,
      maxHeight: 370,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: ThemeColors.navDefault,
    },
    dataContainer: {
      flex: 1,
      flexDirection: "column",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 16,
      backgroundColor: ThemeColors.background,
      width: "80%",
    },
    dataItem: {
      justifyContent: "center",
      alignItems: "center",
    },
    dataItemContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      width: "100%",
      marginBottom: 10,
    },
    icon: {
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 10,
    },
    iconContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      width: "80%",
    },
    iconLabel: {
      color: ThemeColors.text,
      fontSize: 16,
      textAlign: "center",
      marginTop: 5,
    },
    input: {
      width: 150,
      backgroundColor: ThemeColors.editableField,
      borderRadius: 5,
      marginTop: 10,
    },
    label: {
      color: ThemeColors.text,
      fontSize: 16,
      marginBottom: 5,
    },
    saveButton: {
      backgroundColor: ThemeColors.tint,
      borderRadius: 10,
      marginTop: 20,
      marginBottom: 30,
      width: 180,
      height: 55,
      justifyContent: "center",
      alignItems: "center",
    },
  });
